import { Audiowide } from "next/font/google";
import "./globals.css";

const inter = Audiowide({ weight: '400', subsets: ["latin"] });

export const metadata = {
  title: "FCC - Drum Machine",
  description: "FreeCodeCamp Drum Machine Project. Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
